### ISSUE TITLE
Mod lisence

### ISSUE THREAD

**Issue by DwarfyAssassin** [TheChildWalrus/Emmaitar#3]
Hello Mevans,
I have a request about the Emmaitar lisence. 
I wanted to add Emmaitar to my curse forge modpack as a third party mod but to do that I need to submit it to the third party mod list. The rules for the curse forge third party mods are quite strict and one of the rules is that the mods license needs to allow for use in modpacks/redistribution (which most licenses do). If the mod doesn't explicitly have a license the mod is considered as all rights reserved so it can't be added to the third party list. 

So my request is as following could you add a public license file on github, that way the mod will be able to be used as a third party mod in curse forge modpacks.

If you want more info about it you can find it here at the bottom of the page, https://authors.curseforge.com/knowledge-base/game-specific-support/120-how-to-create-a-modpack.

**Comment by TheChildWalrus** [comment]
There you go :) Sorry it took so long.

**Comment by DwarfyAssassin** [comment]
Thanks for the response it got added to the curse forge allowed third party mod list.
